services:
    app:
        build: .
        ports:
            - "3000:3000"
        environment:
            - DB_HOST=mysql
            - DB_USER=root
            - DB_PASSWORD=password
            - DB_NAME=myapp_db
        depends_on:
            - mysql
        volumes:
            - .:/app
            - /app/node_modules

    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=myapp_db
        volumes:
            - mysql_data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "3307:3307"

volumes:
    mysql_data:
